version: '3.5'
services:
  # nodo di bootstrap, non fa mining
  bootstrap:
    volumes:
     - ./eth-node/eth-files/password:/root/files/password:rw
     - ./eth-node/eth-files/genesis:/root/files/genesis:rw
     - ./eth-node/eth-files/keystore:/root/.ethereum/devchain/keystore:rw
     - /etc/localtime:/etc/localtime:ro

  # docker per l'applicazione Web API in dotnet core
  webapi:
    volumes:
      - ./my-webapi/src:/app:rw
      - ./my-webapi/_remote_bin:/app/bin:rw
      - ./my-webapi/_remote_obj:/app/obj:rw

  # nodo per l'applicazione client
  webcli:
    volumes:
      - ./my-wallet/wallet-app:/root/app:rw
      - /root/app/node_modules
      - /etc/localtime:/etc/localtime:ro

  # nodo di monitoring di cosa accade
  netstats:
    volumes:
      - /etc/localtime:/etc/localtime:ro
          
  # nodo peer che farà mining
  eth:
    volumes:
      - ./eth-node/eth-files/password:/root/files/password:ro
      - ./eth-node/eth-files/genesis:/root/files/genesis:ro
      - ./eth-node/eth-files/keystore:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro

  truffle:
    volumes:
      - /app:/usr/src/app:rw
      - /etc/localtime:/etc/localtime:ro

